In [1]:
from pandas import read_csv
import pandas as pd

In [2]:
df = pd.read_csv('https://bit.ly/ds-house-price')
df

지역명               규모구분    연도   월 분양가격(㎡)
0     서울                 전체  2015  10    5841
1     서울         전용면적 60㎡이하  2015  10    5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10    5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10    5721
4     서울        전용면적 102㎡초과  2015  10    5879
...   ..                ...   ...  ..     ...
4500  제주                 전체  2020   2    3955
4501  제주         전용면적 60㎡이하  2020   2    4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2    3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2     NaN
4504  제주        전용면적 102㎡초과  2020   2    3601

[4505 rows x 5 columns]

In [3]:
df = df.rename(columns={'분양가격(㎡)':'분양가격'})
df

지역명               규모구분    연도   월  분양가격
0     서울                 전체  2015  10  5841
1     서울         전용면적 60㎡이하  2015  10  5652
2     서울   전용면적 60㎡초과 85㎡이하  2015  10  5882
3     서울  전용면적 85㎡초과 102㎡이하  2015  10  5721
4     서울        전용면적 102㎡초과  2015  10  5879
...   ..                ...   ...  ..   ...
4500  제주                 전체  2020   2  3955
4501  제주         전용면적 60㎡이하  2020   2  4039
4502  제주   전용면적 60㎡초과 85㎡이하  2020   2  3962
4503  제주  전용면적 85㎡초과 102㎡이하  2020   2   NaN
4504  제주        전용면적 102㎡초과  2020   2  3601

[4505 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   지역명     4505 non-null   object
 1   규모구분    4505 non-null   object
 2   연도      4505 non-null   int64 
 3   월       4505 non-null   int64 
 4   분양가격    4210 non-null   object
dtypes: int64(2), object(3)
memory usage: 176.1+ KB


In [5]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: '  '

In [ ]:
df.loc[df['분양가격'] == '  ', '분양가격'] = '0'

In [ ]:
df['분양가격'].astype(int)

ValueError: cannot convert float NaN to integer

In [ ]:
df['분양가격'] = df['분양가격'].fillna('0')
# fillna = 결측값을 채울 때 사용한다. 

In [ ]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: '6,657'

In [ ]:
df.loc[df['분양가격'] == '6,657']

지역명 규모구분    연도   월   분양가격
2125  서울   전체  2017  11  6,657

In [ ]:
df['분양가격'] = df['분양가격'].str.replace(',', '')

In [ ]:
df.loc[df['분양가격'] == '6657']

지역명 규모구분    연도   월  분양가격
2125  서울   전체  2017  11  6657

In [ ]:
df['분양가격'].astype(int)

ValueError: invalid literal for int() with base 10: '-'

In [ ]:
df['분양가격'] = df['분양가격'].str.replace('-', '0')

In [ ]:
df['분양가격'].astype(int)

0       5841
1       5652
2       5882
3       5721
4       5879
        ... 
4500    3955
4501    4039
4502    3962
4503       0
4504    3601
Name: 분양가격, Length: 4505, dtype: int32

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   지역명     4505 non-null   object
 1   규모구분    4505 non-null   object
 2   연도      4505 non-null   int64 
 3   월       4505 non-null   int64 
 4   분양가격    4505 non-null   object
dtypes: int64(2), object(3)
memory usage: 176.1+ KB


In [ ]:
df['분양가격'] = df['분양가격'].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4505 entries, 0 to 4504
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   지역명     4505 non-null   object
 1   규모구분    4505 non-null   object
 2   연도      4505 non-null   int64 
 3   월       4505 non-null   int64 
 4   분양가격    4505 non-null   int32 
dtypes: int32(1), int64(2), object(2)
memory usage: 158.5+ KB


In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', ' 컴퓨터', '선풍기','선풍기','믹서','믹서']

# LavelEncoder 클래스를 encoder 객체로 생성한후
encoder = LabelEncoder()

# fit은 transfrom 수행 전 틀을 맞춰는 역할
encoder.fit(items)

labels = encoder.transform(items)
print("인코딩 변환값:", labels)

인코딩 변환값: [1 2 5 0 4 4 3 3]


In [ ]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: [' 컴퓨터' 'TV' '냉장고' '믹서' '선풍기' '전자레인지']


In [ ]:
print('디코딩 원본 값:', encoder.inverse_transform([1, 2, 5, 0, 4, 4, 3, 3]))

디코딩 원본 값: ['TV' '냉장고' '전자레인지' ' 컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


- sklearn 에서의 원 핫 인코딩은 복잡하다.
- 첫번째, 먼저 숫자값으로 변환을 위해 LabelEncoder로변환
- 두번째, 2차원 데이터로 변환합니다 (reshape)
- 마지막으로 원-핫 인코딩을 적용
- 원 핫 인코딩(One Hot Encoding)은 카테고리 변수(Categorical Variable)를 머신러닝에서 처리할 수 있는 Binary 벡터(Vector) 값으로 변환해주는 방법을 말 합니다.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기','선풍기','믹서','믹서']

# 첫번째 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [ ]:
# 두번째, 2차원 데이터로 변환
labels = labels.reshape(-1,1)
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [ ]:
# 마지막으로 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print(oh_labels.shape)
oh_labels.toarray()
# toarray 메서드를 이용하면 흔히 사용하는 넘파이 배열로 변환할 수 있지만, 
# 애초에 왜 희소행렬을 반환해주는가 의문이 생깁니다.
# 메모리 문제가 생길 때 고려해볼 수 있는 것이 희소행렬
# 0의 경우 메모리가 빠르게 처리될 수 있다.

(8, 6)


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

판다스의 get_dummies 함수를 이용하면 쉽게 원핫 인코딩이 가능하다.

In [ ]:
import pandas as pd

df = pd.DataFrame({'items':['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기','선풍기','믹서','믹서']})
df

items
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [ ]:
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자렌지  items_컴퓨터
0      True      False     False      False       False      False
1     False       True     False      False       False      False
2     False      False     False      False        True      False
3     False      False     False      False       False       True
4     False      False     False       True       False      False
5     False      False     False       True       False      False
6     False      False      True      False       False      False
7     False      False      True      False       False      False

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)


In [ ]:
print('feature 들의 평균 값')
print(iris_df.mean())
print("\n feature 들의 분산 값")
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

 feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
from sklearn.preprocessing import StandardScaler

# 표준화란 데이터의 평균을 0, 분산과 표준편차를 1로 만들어주는 것을 말하는데요,
# 표준화를 하는 이유는 다른 통계 데이터와 비교하는 데에 있어 용이하게 하기 위함입니다.

# StandardScaler 객체 생성
scaler = StandardScaler()

# standardSacler 로 데이터 셋 변환. fit()과 transfrom() ghcnf
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [ ]:
# transform()시 scale 변환된 데이터 셋이 numpy ndarry로 반환되어 
# 이를 DataFrame으로 변환

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print("feature들의 평균 값")
print(iris_df_scaled.mean())
print("\nfeature 들의 분산 값")
print(iris_df_scaled.var())
iris_df_scaled

feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [ ]:
# MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

# MinManxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 셋 변환. fit()과 transfrom() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [ ]:
# transfrom() 시 scale 변화된 데이터 셋이 numpy ndarry로 반환되어
# 이를 DataFrame으로 변환

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print("feature들의 최소 값")
print(iris_df_scaled.min())
print("\nfeature들의 최대값")
print(iris_df_scaled.max())

feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [7]:
from pandas import read_excel
df = read_excel("https://data.hossam.kr/C02/pre_sample.xlsx", index_col='이름')
# df

In [9]:
df1 = df.copy()
df1['직접합계'] = df['국어'] + df['영어'] + df['수학']+ df['과학']
df1

학년  성별  국어   영어  수학  과학  직접합계
이름                               
철수   1  남자  98   77  88  64   327
영희   2  여자  88  120  62  72   342
민철   1  남자  92   70  83  79   324
수현   3  여자  63   60  31  71   225
호영   4  남자  75   50  90  88   303
영호   4  남자  80   88  91  72   331
용식   2  남자  82   88  79  90   339
나영   1  여자  90   92  81  95   358
석영   1  남자  91   90  89  80   350

In [10]:
df3 = df.copy()
df.iloc[0]# 0번째 행만가져오기

학년     1
성별    남자
국어    98
영어    77
수학    88
과학    64
Name: 철수, dtype: object

In [11]:
df.iloc[1:4]

학년  성별  국어   영어  수학  과학
이름                         
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71

In [12]:
df.iloc[1,2] # 인덱스를 제외하고 1번쨰행 2번째열 수치가져오기

88

In [13]:
df.iloc[:, 3] #모든행에서 3번째 열 값만 가져오기

이름
철수     77
영희    120
민철     70
수현     60
호영     50
영호     88
용식     88
나영     92
석영     90
Name: 영어, dtype: int64

In [14]:
df.iloc[:,2:].sum(axis=1) # 모든 행에 대해서 2번째부터 끝까지의 열값 더하기

이름
철수    327
영희    342
민철    324
수현    225
호영    303
영호    331
용식    339
나영    358
석영    350
dtype: int64

In [15]:
df3 = df.copy()
df3['합계'] = df.iloc[:, 2:].sum(axis=1)
df3

학년  성별  국어   영어  수학  과학   합계
이름                              
철수   1  남자  98   77  88  64  327
영희   2  여자  88  120  62  72  342
민철   1  남자  92   70  83  79  324
수현   3  여자  63   60  31  71  225
호영   4  남자  75   50  90  88  303
영호   4  남자  80   88  91  72  331
용식   2  남자  82   88  79  90  339
나영   1  여자  90   92  81  95  358
석영   1  남자  91   90  89  80  350

In [16]:
df.loc['철수']
df.loc[:, '국어':] # 국어부터 끝까지 열을 선택후 해당되는 모든 행 가져오기
# loc = 이름기반, iloc는 인덱스 번호기반

국어   영어  수학  과학
이름                 
철수  98   77  88  64
영희  88  120  62  72
민철  92   70  83  79
수현  63   60  31  71
호영  75   50  90  88
영호  80   88  91  72
용식  82   88  79  90
나영  90   92  81  95
석영  91   90  89  80

In [17]:
# 평균
df.loc[:, '국어':].mean(axis=1)
# 표준편차
df.loc[:, '국어':].var(axis=1)
# 최대값
df.loc[:, '국어':].max(axis=1)
# 최소값
df.loc[:, '국어':].min(axis=1)
# 한번에 확인하기
df.describe()

학년         국어          영어         수학         과학
count  9.000000   9.000000    9.000000   9.000000   9.000000
mean   2.111111  84.333333   81.666667  77.111111  79.000000
std    1.269296  10.618380   20.481699  19.451507  10.283482
min    1.000000  63.000000   50.000000  31.000000  64.000000
25%    1.000000  80.000000   70.000000  79.000000  72.000000
50%    2.000000  88.000000   88.000000  83.000000  79.000000
75%    3.000000  91.000000   90.000000  89.000000  88.000000
max    4.000000  98.000000  120.000000  91.000000  95.000000

In [1]:
from pandas import read_excel
df = read_excel("https://data.hossam.kr/C02/pre_sample.xlsx", index_col='이름')
df

학년  성별  국어   영어  수학  과학
이름                         
철수   1  남자  98   77  88  64
영희   2  여자  88  120  62  72
민철   1  남자  92   70  83  79
수현   3  여자  63   60  31  71
호영   4  남자  75   50  90  88
영호   4  남자  80   88  91  72
용식   2  남자  82   88  79  90
나영   1  여자  90   92  81  95
석영   1  남자  91   90  89  80

##### skiprows = 불러올 때 행제거